# Generated by Django 6.0 on 2026-01-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='budget',
            new_name='budgetPerHour',
        ),
        migrations.AddField(
            model_name='job',
            name='hours',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
